# Generated by Django 5.0.6 on 2024-05-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=models.DateField(verbose_name='Holiday date'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='occasion',
            field=models.CharField(choices=[('CR', 'CHRISTMAS'), ('NY', 'NEW YEAR'), ('EA', 'EASTER')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='country',
            name='Rivers',
            field=models.ManyToManyField(to='main_app.rivers'),
        ),
    ]
