# Generated by Django 5.0.6 on 2024-05-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rivers_alter_holidays_date_alter_holidays_occasion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidays',
            options={'ordering': ['-date']},
        ),
    ]
